### ISSUE TITLE
Multiple servers design

### ISSUE THREAD

**Issue by fitz123** [autopilotpattern/nginx#21]
My use case is to run few similar containers with ffmpegs as a main app and nginx as co-processor. Container runs with ffmpeg parameters, ffmpeg grabs live stream and produces hls video chunks out of it, I'm using nginx to "share" them.
I spend quite a lot time trying to understand how to run few ffmpeg/nginx containers on the same host, having consul-cluster and load balancer on another accordingly "autopilotpattern". but I gave up.

Major issues:

1. Using _--network bridge_ seems there's no way to find out host's IP adderss and mapped ports from inside container. It the "example" it works great, but inside bridged network only. In case load balancer, consul and app in different hosts - it doesn't work. Unless using _overlay_ driver, but I don't like idea of additional network layer.
2. Using _--network host_ it's quite hard to run multiple consul instances: need to use uniq ports for each, generate uniq node names, and more

The best way I found is to ditch consul agents and use built-in service agent communicated directly with consul server and pass variable for Nginx Port (and Service Port) manually during container creation. 

It works fine but 2 issue don't let me sleep:

1. There's SPoF with containerpilot, which uses only 1st resolved IP address of Consul cluster. Need to perform additional tasks to make eliminate it, like create failover (carp) load balancers in front of consuls or to use docker 1.12 swarm style load balancing from each consul to all
2. Manual ports assignment for every container quite painful 

Did I miss something or there's no better way to deal with my use case?

**Comment by tgross** [comment]
It's a [requirement of the Autopilot Pattern](http://autopilotpattern.io/#what-infrastructure-do-we-need) to have overlay networking so that each container has its own routable IP address. This can mean either via VXLAN as can be found on Joyent's Triton, Docker Swarm w/ the overlay driver, Cisco's Mantl, a project like Weave or Calico, etc. While you can do single-host testing with the out-of-the-box Docker bridge driver, as you've discovered that won't work once you are in a multiple host environment.

**Comment by tgross** [comment]
For what it's worth I think the design you have where you're trying to cram FFMPEG and Nginx into multiple copies of the same container on the same host is going to give you a lot of resource contention problems.

**Comment by fitz123** [comment]
we have already transcoding farm with about 80 servers on bare metal servers
my project is to wrap every job into nginx and let swarm manage scheduling. So should be fine with resource contention

About overlay driver - any possibly drawbacks of using it? I feel that host network is much more reliable in case of node failures, internal networking issues and consul communications (all consul requirements say about using host network only). I see how it suits to autopilot pattern, but what is the cost?

**Comment by tgross** [comment]
> About overlay driver - any possibly drawbacks of using it?

All software defined networking implementations end up with some overhead because they encapsulate packets. So you'll need to tune MTU appropriately. If you were using the overlay network on top of, say, AWS's own software defined networking (VPC) then you'd be further reducing the available MTU for your containers and this could end up being significant.

But if you're co-locating the Nginx and the FFMPEG containers on bare metal anyways, then you might consider having one Nginx front-end container per host (with with _n_ worker processes and host networking) and then have it `--link` all the FFMPEG containers on that same host so that they're not sending chunks thru the network stack at all.

> I feel that host network is much more reliable in case of node failures

On-the-metal host networking of course has fewer moving parts than any sort of software defined networking layer.

That being said here's where I'd highly recommend Joyent's Triton as the best place to run containers on bare metal because you have reliable and proven networking virtualization as part of the kernel w/o the overhead of hardware virtualization. If that doesn't suit you for other reasons then yeah you're going end up with a less-proven network virtualization for containers.

**Comment by tgross** [comment]
Can we close this @fitz123 ?

**Comment by fitz123** [comment]
Yep, can be. Sorry, forgot to close!
I ended up with ffmpeg+nginx as coprocess for each container (so every container is self-sufficient) and 1 consul-agent per host for handling gossip properly with multiple consul servers
