### ISSUE TITLE
Add Let's Encrypt support

### ISSUE THREAD

**Issue by misterbisson** [autopilotpattern/nginx#25]
Automating the process of requesting and renewing SSL certificates via https://letsencrypt.org will require coordination of all Nginx instances serving the same FQDN.

An instance will need to take on the role of the primary in requesting and renewing the certificate, but the certificate and challenges will need to be distributed among all Nginx instances.

Implementing this automation so that Let's Encrypt certificates can be used simply by specifying the FQDN (and minimal other details) in the configuration details would be a great benefit users.

**Comment by tgross** [comment]
Securely redistributing the certificate probably requires that its stored somewhere and that an `task` handler updates it from that location. Otherwise we're talking about having containers reach into each other. What do you think about having the certificate land in a Hashicorp Vault container instead and then distributed via a `task` that has a renewable Vault key?

**Comment by misterbisson** [comment]
Additional documentation for Let's Encrypt implementation: https://certbot.eff.org/#ubuntuxenial-nginx

**Comment by tgross** [comment]
@jasonpincin did some brainstorming on the design for this. In an ideal world we'd probably have the ACME client driven by a task in our scheduler so that the ACME client never has to live on the server. Also, we want to use Vault to distribute certs more securely but in the meantime we want to have a first pass implementation we can try out while the https://github.com/autopilotpattern/vault is in progress.

So here's the outline:
- We run WebDAV in Nginx listening only on the internal network
- A script that runs ACME client will run as a `task` in ContainerPilot (say, every 30 days)
- The script will set a lock in Consul so only one runs per 30 days
- When the ACME client gets back the token from LE, the script POSTs this token to all Nginx instances so that the token is visible on the public Internet
- LE will then check for the token
- The script gets the cert back from LE, and POSTs it to all Nginx instances so the cert is available
- health check for the public IP service will check if cert has changed and SIGHUP Nginx
- toggle all the above behavior with a `LETSENCRYPT` environment flag.

When new instances come online:
- on_change handler obtains a lock in Consul
- winner distributes cert to new instance

**Comment by misterbisson** [comment]
Seems solid, though I have two questions:

Are the certs and keys too big to be placed in the Consul KV store?

**Comment by jasonpincin** [comment]
They're not, but you'd be storing it unencrypted.

**Comment by tgross** [comment]
Yeah, and the Vault implementation will have Consul anyways. So it'd be less work when we switch it out too.

**Comment by jasonpincin** [comment]
This was implemented here: https://github.com/autopilotpattern/nginx/pull/30
